name_or_path: mistral-7b-v0.1
class_name: AutoModelForCausalLM
edit_modules:
- model.layers.26.mlp.down_proj
- model.layers.27.mlp.down_proj
- model.layers.28.mlp.down_proj
- model.layers.29.mlp.down_proj
- model.layers.30.mlp.down_proj
- model.layers.31.mlp.down_proj
half: True
